### ISSUE TITLE
beta3 .deb Ubuntu install just yields an empty window

### ISSUE THREAD

**Issue by ethanwhite** [codeforscience/sciencefair#58] opened 2017-05-04 01:30 UTC
Very exciting project. I'm really looking forward to using it.

When I install `1.0.0-beta3` on Ubuntu 16.04 using the `deb` the install appears to run fine, but when I launch the application I just get an empty gray window:

![screenshot from 2017-05-03 21-23-44](https://cloud.githubusercontent.com/assets/744427/25687817/70065c18-3047-11e7-85fd-3029e0f4ba51.png)

**Comment by phcerdan** [comment] 2017-05-04 05:54
same here in Archlinux. Looking forward to try it!

**Comment by blahah** [comment] 2017-05-04 08:20
Hmm sorry about that @ethanwhite and @phcerdan. I don't have a linux machine to hand right now - could you try right-clicking in the middle of the screen to see if it gives you an 'inspect element' option? If so, you should be able to access the browser console and see any errors. If you could copy-paste them that would be super helpful.

If the above isn't possible I'll find a linux box later this evening to get it sorted. Many thanks.

**Comment by HeidiSeibold** [comment] 2017-05-04 10:00
Right-clicking in the middle does not do anything, unfortunately.

**Comment by phcerdan** [comment] 2017-05-04 10:08
```
module.js:472 Uncaught Error: Cannot find module './lib/contentserver'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (/home/phc/repository_local/sciencefair/node_modules/electron/dist/resources/electron.asar/common/re…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at index.js:2
```

**Comment by ethanwhite** [comment] 2017-05-04 10:20
> Right-clicking in the middle does not do anything, unfortunately.

Same for me.

**Comment by rgieseke** [comment] 2017-05-04 10:27
After editing `/opt/ScienceFair/resources/app/index.js` (with sudo) and adding 

```javascript
  main.webContents.openDevTools()
```
I get the same error message. Right-clicking didn't work for me either.

**Comment by blahah** [comment] 2017-05-04 10:33
Thanks all, the issue is to do with case-sensitivity of require being different between linux/macos. I'm pushing out a fix now. I also discovered why the devtools aren't working - they'll be enabled in the next beta.

**Comment by blahah** [comment] 2017-05-04 10:35
Also, to fix locally you can rename `ScienceFair/resources/app/client/lib/contentServer.js` to `ScienceFair/resources/app/client/lib/contentserver.js` 🙄

**Comment by blahah** [comment] 2017-05-04 13:04
Should be fixed in beta4, currently building on the CI servers: https://github.com/codeforscience/sciencefair/releases/tag/v1.0.0-beta4. Once the builds are ready they will automatically be added as downloads to that release :)

**Comment by blahah** [comment] 2017-05-04 19:12
can anyone confirm whether this issue is resolved in beta4?

**Comment by phcerdan** [comment] 2017-05-04 23:32
Working from current master in Arch. Thanks!

**Comment by blahah** [comment] 2017-05-04 23:54
w00p, thanks @phcerdan

**Closed** 2017-05-04 23:54 UTC
